"""Added country column

Revision ID: 9be554af86df
Revises: 
Create Date: 2024-10-10 18:43:36.629965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be554af86df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=32), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
